title: Clean Blog
email: sumeet.mathpati@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple and minimal jekyll theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Personal information
first_name: Jane 
last_name: Doe
avatar: "/assets/images/avatar_g.jpg"
about: "I am a software engineering student. I am computer science and engineering undergrad. I love to FOSS. When I am not using computer I like to watch movies, TV shows, read books."

# Social media links
github: "https://github.com/"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
facebook: "https://www.facebook.com/"
instagram: "https://www.instagram.com/"

# Quote to show on site
quote: "Proprietary software is an injustice."
quote_author: "Richard Stallman"

permalink: /:title/
include: ["_pages"]
favicon: "./logo.png" # relative path to site's favicon
goat_counter: "" # put your GoatCounter name if you want to use GoatCounter analytics

# Pagination 
# paginate: 9
# paginate_path: /page:num/

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-paginate

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge